"""Teacher-student distillation with stateful truncated BPTT.

Scope: privileged teacher -> deployable student, behaviour cloning only. There is no critic,
no GAE, no PPO surrogate and no RL fine-tuning stage, so this algorithm deliberately does not
inherit from :class:`~instinct_rl.algorithms.ppo.PPO` or
:class:`~instinct_rl.algorithms.tppo.TPPO`.

Two properties drive the design, both of which matter far more for a *recurrent* student than
for an MLP one:

1. **The student's carry is recomputed, never replayed from the buffer.** PPO's recurrent
   minibatch generator starts every BPTT segment from the hidden state saved during rollout.
   After a few epochs of updates those saved states were produced by stale weights. Here the
   rollout is replayed forward in time and the carry is produced by the weights currently
   being trained. The residual staleness is one optimizer step at each TBPTT chunk boundary --
   not zero, but bounded and small (see ``refresh_hidden_after_update``).

2. **The environment always executes the student's action.** The teacher only ever produces
   labels. Mixing teacher actions into the rollout (as TPPO's ``teacher_act_prob`` does) makes
   the student's RNN learn its memory on state sequences generated by a mixture policy, while
   at deployment the sequence is student-only. Because a carry is a cumulative quantity, that
   mismatch compounds over time.

The teacher is an independent, frozen policy object. It is never touched by ``update()``, so
its own recurrent carry stays continuous across iterations, and its architecture is completely
decoupled from the student's.
"""

import contextlib
import os
import os.path as osp
import time

import torch
import torch.distributed as dist
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import yaml

import instinct_rl.modules as modules
from instinct_rl.storage.distillation_storage import DistillationStorage
from instinct_rl.utils.utils import get_subobs_size


def _is_critic_key(key: str) -> bool:
    """Whether a state-dict key belongs to the value-function half of an actor-critic."""
    return key.startswith(("critic", "critics", "memory_c", "critic_encoders"))


class TeacherPolicy:
    """A frozen, checkpoint-loaded policy that only ever produces deterministic action labels.

    Owns everything teacher-side that the rest of the system should not have to think about:
    building the network, loading the checkpoint, loading and freezing the teacher's *own*
    observation normalizer, and maintaining its recurrent carry across the whole training run.

    Observation normalization ownership: the teacher normalizes its input itself, with the
    normalizer stored in its checkpoint. The runner must therefore *not* configure a
    normalizer for the observation group that feeds the teacher, or the observations get
    normalized twice. :class:`~instinct_rl.runners.distillation_runner.DistillationRunner`
    checks this at construction time.
    """

    def __init__(
        self,
        policy_class_name,
        policy_cfg,
        obs_format,
        num_actions,
        num_rewards,
        logdir=None,
        checkpoint=None,
        allow_random_teacher=False,
        device="cpu",
    ):
        self.device = device
        self.logdir = logdir
        self.checkpoint = checkpoint

        # An absolute `checkpoint` is enough to find the weights on its own -- `_resolve_model_path`
        # already handles it -- but the normalizer lives at `<logdir>/params/agent.yaml`, so the
        # run directory is derived from the checkpoint rather than the pair being silently
        # ignored. Without this, `teacher_checkpoint="/abs/path/model.pt"` with no `teacher_logdir`
        # trained happily against a *randomly initialized* teacher.
        if self.logdir is None and self.checkpoint is not None:
            if not osp.isabs(self.checkpoint):
                raise ValueError(
                    f"teacher_checkpoint={self.checkpoint!r} is a relative path but no teacher_logdir"
                    " was given, so it cannot be resolved. Pass teacher_logdir, or make the"
                    " checkpoint path absolute."
                )
            self.logdir = osp.dirname(self.checkpoint)

        policy_cfg = dict(policy_cfg)
        # The teacher's actor was trained on its own "policy" group. When distilling from a
        # privileged teacher, that group is whatever group of the *current* env we feed it
        # (usually "critic"); the caller has already resolved this into `obs_format`.
        policy_cfg.setdefault("obs_format", obs_format)
        # Keep the *raw* observation format: the normalizer is sized on it. Reading it back off
        # the built policy would not work -- ActorCriticRecurrent.obs_segments describes its MLP
        # head's input (the RNN latent), not the observations entering the network.
        self.obs_format = policy_cfg["obs_format"]

        self.policy = modules.build_actor_critic(
            policy_class_name,
            policy_cfg,
            policy_cfg["obs_format"],
            num_actions=num_actions,
            num_rewards=num_rewards,
        ).to(device)
        self.normalizer = None

        if self.logdir is None:
            # A random teacher produces a perfectly smooth, perfectly meaningless loss curve --
            # the student learns to imitate noise and nothing anywhere else complains. That is a
            # failure mode worth an exception rather than a line of yellow text in a log nobody
            # reads until the run has burned a day of GPU.
            if not allow_random_teacher:
                raise ValueError(
                    "No teacher checkpoint was given (both teacher_logdir and teacher_checkpoint are"
                    " None), so the teacher would be randomly initialized and every action label"
                    " meaningless. Set teacher_logdir (and optionally teacher_checkpoint), or pass"
                    " allow_random_teacher=True if an untrained teacher is genuinely intended."
                )
            print(
                "\033[43;33mDistillation warning: allow_random_teacher is set; the teacher is randomly"
                " initialized and its labels are meaningless.\033[0m"
            )
        else:
            self._load()

        self.policy.eval()
        self.policy.requires_grad_(False)

    """
    Checkpoint loading
    """

    def _resolve_model_path(self):
        if self.checkpoint is not None:
            return self.checkpoint if osp.isabs(self.checkpoint) else osp.join(self.logdir, self.checkpoint)
        model_files = [f for f in os.listdir(self.logdir) if f.endswith(".pt") and f.startswith("model_")]
        if not model_files:
            raise FileNotFoundError(f"No model_*.pt checkpoint found in teacher logdir {self.logdir}")
        model_files.sort(key=lambda f: int(f.split(".")[0].split("_")[1]))
        return osp.join(self.logdir, model_files[-1])

    def _load(self):
        model_path = self._resolve_model_path()
        print(f"Distillation: loading teacher policy from {model_path}")
        state_dict = torch.load(model_path, map_location="cpu")

        # The teacher's critic is never used for distillation, and its observation group may not
        # even exist in the distillation env, so a *shape* mismatch there is not an error --
        # a privileged teacher whose value function additionally saw a height scan is the normal
        # case, not an exotic one. `strict=False` alone does not cover this: it tolerates missing
        # and unexpected keys but still raises on a size mismatch for a key that is present. So
        # the mismatched critic tensors are dropped before loading.
        #
        # Everything on the actor path, by contrast, must match exactly -- a silently unloaded
        # actor layer would produce plausible-looking but wrong labels for the entire run -- so
        # shape mismatches there are collected and re-raised with the diagnostic below.
        checkpoint_state = state_dict["model_state_dict"]
        own_state = self.policy.state_dict()
        loadable = {}
        actor_mismatched = []
        skipped_critic = []
        for key, value in checkpoint_state.items():
            if key in own_state and own_state[key].shape != value.shape:
                detail = f"{key}: checkpoint {tuple(value.shape)} vs model {tuple(own_state[key].shape)}"
                if _is_critic_key(key):
                    skipped_critic.append(detail)
                else:
                    actor_mismatched.append(detail)
                continue
            loadable[key] = value

        missing, unexpected = self.policy.load_state_dict(loadable, strict=False)
        actor_missing = [k for k in missing if not _is_critic_key(k)]
        actor_unexpected = [k for k in unexpected if not _is_critic_key(k)]
        if actor_missing or actor_unexpected or actor_mismatched:
            raise RuntimeError(
                "Teacher checkpoint does not match the configured teacher architecture on the actor"
                f" path.\n  missing keys:      {actor_missing}\n  unexpected keys:   {actor_unexpected}\n"
                f"  shape mismatches:  {actor_mismatched}\n"
                "Check `teacher_policy_class_name` and `teacher_policy` against the run that produced"
                f" {model_path}."
            )
        if skipped_critic:
            print(
                "Distillation: ignoring the teacher's value function, whose observation group does not"
                f" match this env ({len(skipped_critic)} tensor(s) skipped, e.g. {skipped_critic[0]})."
                " Only the actor is used for labelling, so this is expected for a privileged teacher."
            )

        self._load_normalizer(state_dict)

    def _load_normalizer(self, state_dict):
        if "policy_normalizer_state_dict" not in state_dict:
            return
        agent_cfg_path = osp.join(self.logdir, "params", "agent.yaml")
        if not osp.isfile(agent_cfg_path):
            raise FileNotFoundError(
                f"Teacher checkpoint carries a policy normalizer but {agent_cfg_path} is missing, so"
                " the normalizer class/kwargs cannot be reconstructed."
            )
        with open(agent_cfg_path) as f:
            agent_cfg = yaml.full_load(f)
        normalizer_cfg = dict(agent_cfg["normalizers"]["policy"])
        self.normalizer = modules.build_normalizer(
            input_shape=get_subobs_size(self.obs_format["policy"]),
            normalizer_class_name=normalizer_cfg.pop("class_name"),
            normalizer_kwargs=normalizer_cfg,
        )
        self.normalizer.to(self.device)
        self.normalizer.load_state_dict(state_dict["policy_normalizer_state_dict"])
        self.normalizer.eval()
        self.normalizer.requires_grad_(False)
        print("Distillation: loaded and froze the teacher's own observation normalizer.")

    """
    Labelling
    """

    @torch.no_grad()
    def act_inference(self, obs):
        """Deterministic teacher action mean, and the only thing the student is trained on."""
        if self.normalizer is not None:
            obs = self.normalizer(obs)
        return self.policy.act_inference(obs)

    def reset(self, dones):
        """Reset the teacher's own carry at episode boundaries. Called from rollout only."""
        self.policy.reset(dones)


class Distillation:
    """Behaviour-cloning a privileged teacher into a deployable (usually recurrent) student."""

    def __init__(
        self,
        actor_critic,
        # -- teacher
        teacher_logdir=None,
        teacher_checkpoint=None,
        teacher_policy_class_name="ActorCriticRecurrent",
        teacher_policy=None,
        teacher_obs_source="critic",
        allow_random_teacher=False,
        warm_start_from_teacher=False,
        # -- loss
        loss_type="mse_sum",
        # -- optimisation
        gradient_length=24,
        normalize_accumulated_loss=True,
        flush_tail=True,
        accumulate_gradients=False,
        learning_rate=3.0e-4,
        max_grad_norm=1.0,
        optimizer_class_name="Adam",
        freeze_action_std=True,
        ema_decay=None,
        # -- recurrent bookkeeping
        refresh_hidden_after_update=False,
        # -- lr schedule
        lr_scheduler_class_name=None,
        lr_scheduler=None,
        lr_scheduler_step_unit="optimizer_step",
        device="cpu",
        **kwargs,
    ):
        """
        Args:
            teacher_obs_source: which observation group of the *current* env feeds the teacher's
                actor. "critic" for the usual privileged-teacher setup, "policy" when teacher and
                student share an observation space.
            warm_start_from_teacher: copy every teacher weight the student can accept -- memory,
                actor head, MoE gate -- leaving only the exteroceptive encoder (``encoders.*``)
                and the action std randomly initialized.

                This only applies when teacher and student are architecturally identical apart
                from that encoder, which is the setup *Now You See That* describes: "the teacher
                and student policies share identical architectures except for their exteroceptive
                encoders ... the depth encoder output replaces the height scan embedding".

                It changes what the run is learning. Cold-started, the student must rediscover
                locomotion from a state distribution consisting entirely of falling, because a
                student-only rollout never produces anything else until it can walk. Warm-started,
                the locomotion policy is already there and the only thing being learned is a
                depth encoder that produces latents the inherited network can already use --
                which is also why no explicit teacher/student latent-matching loss is needed:
                the action loss forces that alignment through the frozen-in-place downstream net.

                Nothing is frozen, so the inherited weights still adapt.
            gradient_length: TBPTT chunk length, in environment steps. Decoupled from
                ``num_steps_per_env`` on purpose: the rollout length sets how much data an
                iteration sees, this sets how deep gradients flow.
            normalize_accumulated_loss: average the per-step losses over a chunk instead of
                summing them, so the effective step size does not scale with ``gradient_length``.
            flush_tail: run a final optimizer step on the leftover steps when the rollout is not
                an exact multiple of ``gradient_length``. Without it those steps produce no
                gradient at all while still appearing in the logged loss.
            accumulate_gradients: accumulate every TBPTT chunk's gradient and take a *single*
                clipped optimizer step per rollout, instead of one step per chunk. Two effects
                worth knowing:

                * The weights do not change *during* the replay, so every chunk is differentiated
                  at the same parameter version. This removes the inter-chunk weight skew, but
                  **not** all staleness: the optimizer step happens after the replay, so the
                  carry handed to the next rollout was still produced by the pre-step weights.
                  What changes is that the staleness becomes uniform and exactly one optimizer
                  step, instead of a mixture spanning the whole update.
                  ``refresh_hidden_after_update`` is what removes that remaining step, and it
                  stays useful here -- arguably more so, since one refresh now cancels the only
                  skew left.
                * ``max_grad_norm`` then clips the whole rollout's gradient rather than one
                  chunk's, and the lr schedule advances once per iteration instead of
                  ``ceil(T/G)`` times. Both change what a given hyper-parameter means, which is
                  why this is opt-in rather than the default.
            ema_decay: if set, maintain an exponential moving average of the student weights,
                updated after every optimizer step, and checkpoint *those* as the deployable
                model. ``None`` disables it. 0.997 gives roughly a 330-step averaging horizon.
            refresh_hidden_after_update: after all optimizer steps, replay the rollout once more
                under ``no_grad`` with the final weights and use *that* as the next rollout's
                carry. Costs one extra sequential forward pass over the rollout and only removes
                a one-optimizer-step-old carry, so it is off by default; keep it as an ablation.
        """
        if kwargs:
            # Distillation shares a config slot with PPO/TPPO, so a half-ported config is the
            # normal way to arrive here: `num_learning_epochs`, `num_mini_batches`,
            # `teacher_act_prob`, `distill_target`, `buffer_dilation_ratio`, `denoise_loss_coef`
            # are all silently meaningless to this algorithm. So is a typo like `gradient_lenght`,
            # which would leave gradient_length at its default. A warning is not enough: the run
            # trains fine, finishes, and its recorded config does not describe what actually ran.
            raise TypeError(
                f"Distillation got unknown config keys: {sorted(kwargs)}.\n"
                "These have no effect here. If this config was ported from PPO/TPPO, remove the"
                " keys that do not apply (num_learning_epochs, num_mini_batches, teacher_act_prob,"
                " distill_target, buffer_dilation_ratio, hidden_state_resample_prob, ...); if one"
                " is a typo, check it against the Distillation signature."
            )

        if not (isinstance(gradient_length, int) and gradient_length > 0):
            raise ValueError(f"gradient_length must be a positive integer, got {gradient_length!r}")
        # 0.0 is allowed on purpose: it freezes the weights while still populating .grad, which
        # is how the tests inspect gradients without the update perturbing what they measure.
        if learning_rate < 0:
            raise ValueError(f"learning_rate must be non-negative, got {learning_rate!r}")
        if max_grad_norm is not None and not max_grad_norm > 0:
            raise ValueError(f"max_grad_norm must be positive or None, got {max_grad_norm!r}")

        self.device = device
        self.actor_critic = actor_critic
        self.actor_critic.to(self.device)

        self.teacher_obs_source = teacher_obs_source
        self.warm_start_from_teacher = warm_start_from_teacher
        if teacher_obs_source not in ("policy", "critic"):
            raise ValueError(f"teacher_obs_source must be 'policy' or 'critic', got {teacher_obs_source!r}")

        self.loss_type = loss_type
        self.gradient_length = gradient_length
        self.normalize_accumulated_loss = normalize_accumulated_loss
        self.flush_tail = flush_tail
        self.accumulate_gradients = accumulate_gradients
        self.learning_rate = learning_rate
        self.max_grad_norm = max_grad_norm
        self.refresh_hidden_after_update = refresh_hidden_after_update
        self.lr_scheduler_step_unit = lr_scheduler_step_unit
        if lr_scheduler_step_unit not in ("optimizer_step", "update"):
            raise ValueError(
                f"lr_scheduler_step_unit must be 'optimizer_step' or 'update', got {lr_scheduler_step_unit!r}"
            )

        # The behaviour-cloning loss is a function of the student's action *mean* only, so the
        # exploration std never receives a gradient. Freezing it makes that explicit instead of
        # leaving a parameter that looks trainable but silently never moves.
        if freeze_action_std and hasattr(self.actor_critic, "std"):
            self.actor_critic.std.requires_grad_(False)

        self.trainable_parameters = [p for p in self.actor_critic.parameters() if p.requires_grad]
        self.optimizer = getattr(optim, optimizer_class_name)(self.trainable_parameters, lr=learning_rate)

        self.lr_scheduler = None
        if lr_scheduler_class_name is not None:
            self.lr_scheduler = getattr(optim.lr_scheduler, lr_scheduler_class_name)(
                self.optimizer, **(lr_scheduler or {})
            )

        # Weight EMA. The shadow copy is keyed off the full state_dict rather than just the
        # parameters so that any buffer a student carries survives a checkpoint round-trip;
        # non-floating-point entries are copied rather than averaged.
        if ema_decay is not None and not 0.0 < ema_decay < 1.0:
            raise ValueError(f"ema_decay must be in (0, 1) or None, got {ema_decay!r}")
        self.ema_decay = ema_decay
        self._ema_state = None
        if ema_decay is not None:
            self._ema_state = {k: v.detach().clone() for k, v in self.actor_critic.state_dict().items()}

        # Teacher is built lazily in init_storage(), where the env's obs_format is available.
        self._teacher_cfg = dict(
            logdir=teacher_logdir,
            checkpoint=teacher_checkpoint,
            allow_random_teacher=allow_random_teacher,
            policy_class_name=teacher_policy_class_name,
            policy_cfg=dict(teacher_policy or {}),
        )
        self.teacher = None
        self.storage = None

        # The carry the current rollout started from. `update()` replays from here rather than
        # from wherever the rollout left the policy, so the replay reproduces the same state
        # sequence with fresh weights. None means "zeros", which is also the state at iteration 0.
        self._rollout_start_hidden = None
        self._pending_student_obs = None
        self._pending_teacher_mean = None

        self.current_learning_iteration = 0
        self.optimizer_step_count = 0

    """
    Setup
    """

    def init_storage(self, num_envs, num_transitions_per_env, obs_format, num_actions, num_rewards=1):
        student_obs_size = int(get_subobs_size(obs_format["policy"]))
        self.storage = DistillationStorage(
            num_envs,
            num_transitions_per_env,
            student_obs_shape=(student_obs_size,),
            actions_shape=(num_actions,),
            device=self.device,
        )

        teacher_cfg = dict(self._teacher_cfg)
        policy_cfg = teacher_cfg.pop("policy_cfg")
        if "obs_format" not in policy_cfg:
            # The teacher's actor consumes the chosen group of the current env. Its critic is
            # never evaluated, so pointing it at the same group is harmless and avoids forcing
            # the user to restate the teacher's full obs_format in the config.
            if self.teacher_obs_source not in obs_format:
                raise KeyError(
                    f"teacher_obs_source={self.teacher_obs_source!r} is not an observation group of this"
                    f" env (available: {list(obs_format)}). Either change it or provide an explicit"
                    " `teacher_policy.obs_format`."
                )
            group = obs_format[self.teacher_obs_source]
            policy_cfg["obs_format"] = {"policy": group, "critic": group}
        else:
            self._check_teacher_obs_matches_env(obs_format, policy_cfg["obs_format"])

        self.teacher = TeacherPolicy(
            policy_cfg=policy_cfg,
            obs_format=policy_cfg["obs_format"],
            num_actions=num_actions,
            num_rewards=num_rewards,
            device=self.device,
            **teacher_cfg,
        )

        if self.warm_start_from_teacher:
            self._warm_start()

    def _check_teacher_obs_matches_env(self, env_obs_format, teacher_obs_format):
        """Verify the env group feeding the teacher matches the layout the teacher was built for.

        Only reachable when `teacher_policy.obs_format` is given explicitly. The teacher is then
        built from that declaration, not from the env, so the two can disagree -- and nothing
        downstream notices. `ParallelLayer` slices the incoming tensor by the *declared* segment
        sizes, so a longer observation is silently truncated and a shorter one silently
        reinterprets neighbouring components. The teacher goes on producing confident,
        meaningless labels and the student faithfully imitates them.

        Observed once: the env's `critic` group was changed to history-stacked observations
        (proprio x8, height scan x4 -> 3540 dims) while the teacher was still declared on the
        single-frame layout (789 dims). The run trained for 8.3 hours; every episode ended in
        base contact within ~15 steps and the terrain curriculum never left level 0.
        """
        group = env_obs_format.get(self.teacher_obs_source)
        if group is None:
            raise KeyError(
                f"teacher_obs_source={self.teacher_obs_source!r} is not an observation group of this"
                f" env (available: {list(env_obs_format)})."
            )
        declared = teacher_obs_format["policy"]
        env_size, declared_size = int(get_subobs_size(group)), int(get_subobs_size(declared))
        if env_size == declared_size:
            return

        def _terms(fmt):
            return "\n".join(f"      {k:24s} {tuple(v)}" for k, v in fmt.items())

        raise ValueError(
            f"The env's '{self.teacher_obs_source}' observation group is {env_size} values, but"
            f" `teacher_policy.obs_format['policy']` declares {declared_size}. That group is what"
            " feeds the teacher, so the mismatch would be silently sliced rather than raised, and"
            " every action label would be meaningless.\n"
            f"  env['{self.teacher_obs_source}'] ({env_size}):\n{_terms(group)}\n"
            f"  teacher_policy.obs_format['policy'] ({declared_size}):\n{_terms(declared)}\n"
            "Usually one side gained or lost observation history (a term's `history_length`), or"
            " a term was renamed. Make the env group match the layout the teacher was trained on,"
            " or drop `teacher_policy.obs_format` entirely to derive it from the env."
        )

    # Weights the student must learn for itself rather than inherit: the exteroceptive encoder
    # is the whole point of the distillation (a different sensor modality entirely), and the
    # action std is a deliberate config choice -- the teacher explores at 1.0, the student is
    # meant to stay at its own constant (0.1 in the paper).
    _WARM_START_EXCLUDE = ("encoders.", "std")

    def _warm_start(self):
        """Seed the student with every teacher weight it can accept. See ``warm_start_from_teacher``."""
        teacher_state = self.teacher.policy.state_dict()
        student_state = self.actor_critic.state_dict()

        to_load, inherited, excluded, incompatible = {}, [], [], []
        for key, value in student_state.items():
            if key.startswith(self._WARM_START_EXCLUDE):
                excluded.append(key)
            elif key not in teacher_state or teacher_state[key].shape != value.shape:
                incompatible.append(key)
            else:
                to_load[key] = teacher_state[key]
                inherited.append(key)

        # The locomotion policy *is* the memory plus the actor head. If any of it failed to
        # transfer, the warm start did not do the one thing it exists to do -- and the run would
        # continue from a half-seeded network while the log claims it was warm-started, which is
        # worse than not offering the option at all. Encoder and critic gaps are expected and fine.
        critical = sorted({k for k in incompatible if k.startswith(("memory_a.", "actor."))})
        if critical or not inherited:
            raise RuntimeError(
                "warm_start_from_teacher could not transfer the student's locomotion policy:"
                f" {len(critical)} actor/memory tensor(s) are absent from the teacher or a"
                f" different shape, e.g. {critical[:4]}.\n"
                "This option assumes teacher and student are identical apart from the"
                " exteroceptive encoder. Check rnn_hidden_size / rnn_num_layers /"
                " actor_hidden_dims / num_moe_experts / moe_gate_hidden_dims against the teacher,"
                " and that both encoders emit the same latent width (the GRU input is"
                " proprio + latent, so a differing latent size shifts every recurrent weight)."
            )

        self.actor_critic.load_state_dict(to_load, strict=False)

        def _modules(keys):
            return sorted({k.split(".")[0] for k in keys})

        print(
            f"Distillation: warm-started the student from the teacher -- inherited"
            f" {len(inherited)} tensors {_modules(inherited)}, left {len(excluded)} to be learned"
            f" {_modules(excluded)}."
        )
        if incompatible:
            print(
                "\033[43;33mDistillation warning: warm start could not transfer"
                f" {len(incompatible)} tensor(s) {_modules(incompatible)} -- absent from the"
                " teacher or a different shape. The student is only partly seeded; if this list"
                " is not what you expect, teacher and student are not as architecturally aligned"
                " as warm_start_from_teacher assumes.\033[0m"
            )

    """
    Rollout
    """

    def act(self, obs, critic_obs):
        """Return the action the environment will execute -- always the student's, never the teacher's."""
        teacher_obs = critic_obs if self.teacher_obs_source == "critic" else obs
        if teacher_obs is None:
            raise ValueError(
                "teacher_obs_source='critic' but the environment produced no critic observations."
            )

        self._pending_teacher_mean = self.teacher.act_inference(teacher_obs).detach()
        # Cloned, not aliased. This observation is only copied into storage after env.step()
        # returns, and an environment that writes its observations into a reused buffer would by
        # then have overwritten it with obs[t+1] -- pairing obs[t+1] with the label for obs[t],
        # a one-step misalignment that no loss curve would reveal. IsaacLab usually allocates a
        # fresh tensor per step, and a configured normalizer makes a fresh one regardless, but
        # correctness here should not depend on either.
        self._pending_student_obs = obs.detach().clone()
        # Sampled, not the mean: the exploration noise is what gives the student state coverage
        # beyond the trajectory band it would otherwise stay on. std is frozen, so this is a
        # constant-width perturbation throughout training.
        return self.actor_critic.act(obs).detach()

    def process_env_step(self, rewards, dones, infos, next_obs, next_critic_obs):
        self.storage.add(self._pending_student_obs, self._pending_teacher_mean, dones)
        self._pending_student_obs = None
        self._pending_teacher_mean = None
        # Student and teacher keep separate carries and are reset independently.
        self.actor_critic.reset(dones)
        self.teacher.reset(dones)

    def compute_returns(self, last_critic_obs):
        """No-op. Behaviour cloning has no value function.

        Kept so :class:`~instinct_rl.runners.on_policy_runner.OnPolicyRunner` can drive this
        algorithm unchanged; duplicating its ~90-line rollout/bookkeeping loop just to delete
        one call would be a worse trade than this two-line stub.
        """
        return None

    """
    Update
    """

    def _behavior_loss(self, student_mean, teacher_mean):
        """Per-timestep behaviour loss: reduce over the action dimension, mean over envs."""
        diff = student_mean - teacher_mean
        if self.loss_type == "mse_sum":
            per_env = diff.square().sum(dim=-1)
        elif self.loss_type == "mse":
            per_env = diff.square().mean(dim=-1)
        elif self.loss_type == "l1":
            per_env = diff.abs().sum(dim=-1)
        elif self.loss_type == "huber":
            per_env = F.huber_loss(student_mean, teacher_mean, reduction="none").sum(dim=-1)
        else:
            raise ValueError(f"Unknown loss_type: {self.loss_type!r}")
        return per_env.mean()

    def _chunk_plan(self):
        """``(num_chunks, graded_steps)`` for the rollout currently in storage.

        ``graded_steps`` counts only the steps that will actually produce a gradient, so a
        dropped tail (``flush_tail=False``) does not dilute the accumulated loss.
        """
        total = len(self.storage)
        full, tail = divmod(total, self.gradient_length)
        if tail and self.flush_tail:
            return full + 1, total
        return full, full * self.gradient_length

    def _chunk_loss(self, chunk_losses, graded_steps):
        """Scalar loss for one TBPTT chunk, scaled for how it will be consumed.

        Under accumulation the chunk losses are summed and divided by the rollout's *total*
        graded step count, so that the gradient accumulated across all chunks equals the
        gradient of the mean per-step loss over the whole rollout. Weighting by chunk length
        rather than by ``1/num_chunks`` matters when a short tail chunk exists: dividing every
        chunk equally would give a 5-step tail the same pull as an 80-step chunk.
        """
        stacked = torch.stack(chunk_losses)
        if not self.normalize_accumulated_loss:
            return stacked.sum()
        if self.accumulate_gradients:
            return stacked.sum() / max(graded_steps, 1)
        return stacked.mean()

    def _backward_chunk(self, chunk_losses, graded_steps):
        """Backward one TBPTT chunk.

        Returns ``(norm_before, norm_after)`` when this chunk also triggered an optimizer step,
        or ``None`` when its gradient was merely accumulated for a single step taken at the end
        of :meth:`update`.
        """
        loss = self._chunk_loss(chunk_losses, graded_steps)
        if self.accumulate_gradients:
            loss.backward()  # gradients pile up in .grad; zero_grad happened in update()
            return None
        self.optimizer.zero_grad(set_to_none=True)
        loss.backward()
        return self._step()

    def _step(self):
        """Clip whatever is currently in ``.grad`` and take one optimizer step."""
        if dist.is_initialized():
            raise NotImplementedError(
                "Distillation does not support distributed training yet. Gradients must be"
                " all-reduced before *each* optimizer step in an update, not once per update;"
                " see HANDOFF.md."
            )

        # clip_grad_norm_ returns the total norm *before* clipping, so both numbers come free.
        max_norm = self.max_grad_norm if self.max_grad_norm is not None else float("inf")
        norm_before = nn.utils.clip_grad_norm_(self.trainable_parameters, max_norm)
        norm_after = torch.clamp(norm_before, max=max_norm)

        self.optimizer.step()
        self.optimizer_step_count += 1
        self._update_ema()
        if self.lr_scheduler is not None and self.lr_scheduler_step_unit == "optimizer_step":
            self.lr_scheduler.step()
            self.learning_rate = self.optimizer.param_groups[0]["lr"]

        return norm_before.detach(), norm_after.detach()

    @torch.no_grad()
    def _update_ema(self):
        if self._ema_state is None:
            return
        decay = self.ema_decay
        for key, value in self.actor_critic.state_dict().items():
            shadow = self._ema_state[key]
            if shadow.dtype.is_floating_point:
                shadow.mul_(decay).add_(value.detach(), alpha=1.0 - decay)
            else:
                shadow.copy_(value)  # e.g. integer counters -- averaging them is meaningless

    @contextlib.contextmanager
    def use_student_weights(self, which="ema"):
        """Temporarily install a different weight set on the live student, then restore.

        Checkpoints store the EMA weights as ``model_state_dict``, but ``get_inference_policy``,
        ``export_as_jit`` and ``export_as_onnx`` all read ``alg.actor_critic`` directly, so
        without this an export silently ships weights the checkpoint does not contain::

            with alg.use_student_weights("ema"):
                runner.export_as_onnx(...)

        Restoring on exit is what makes this safe to use mid-training: the optimizer state
        belongs to the raw weights, so leaving the average installed would corrupt the next step.
        """
        if which not in ("raw", "ema"):
            raise ValueError(f"which must be 'raw' or 'ema', got {which!r}")
        if which == "raw" or self._ema_state is None:
            if which == "ema":
                raise RuntimeError("No EMA is being maintained; construct Distillation with ema_decay.")
            yield self.actor_critic
            return

        saved = {k: v.detach().clone() for k, v in self.actor_critic.state_dict().items()}
        self.actor_critic.load_state_dict(self._ema_state)
        try:
            yield self.actor_critic
        finally:
            self.actor_critic.load_state_dict(saved)

    def load_ema_into_model(self):
        """Destructively overwrite the live student with its EMA weights.

        Prefer :meth:`use_student_weights`, which restores afterwards. Training must not continue
        after this call -- the optimizer state belongs to the raw weights, not the averaged ones.
        """
        if self._ema_state is None:
            raise RuntimeError("No EMA is being maintained; construct Distillation with ema_decay.")
        self.actor_critic.load_state_dict(self._ema_state)

    def update(self, current_learning_iteration):
        self.current_learning_iteration = current_learning_iteration
        policy = self.actor_critic

        # Replay from where the rollout began, not from where it ended: the point is to
        # regenerate the carry with the weights being trained.
        policy.set_actor_hidden_state(self._rollout_start_hidden)

        _, graded_steps = self._chunk_plan()

        zero = torch.zeros((), device=self.device)
        behavior_loss_sum = zero.clone()
        action_l2_sum = zero.clone()
        action_err_max = zero.clone()
        norm_before_sum = zero.clone()
        norm_after_sum = zero.clone()
        num_steps = 0
        optimizer_steps = 0
        tail_chunk_size = 0
        chunk_losses = []

        if self.accumulate_gradients:
            # One zeroing for the whole rollout: every chunk below adds into .grad.
            self.optimizer.zero_grad(set_to_none=True)

        for student_obs, teacher_mean, dones in self.storage.iter_timesteps():
            student_mean = policy.act_inference(student_obs)
            step_loss = self._behavior_loss(student_mean, teacher_mean)
            chunk_losses.append(step_loss)
            num_steps += 1

            with torch.no_grad():
                diff = student_mean - teacher_mean
                behavior_loss_sum += step_loss.detach()
                action_l2_sum += diff.norm(dim=-1).mean()
                action_err_max = torch.maximum(action_err_max, diff.abs().max())

            if len(chunk_losses) == self.gradient_length:
                stepped = self._backward_chunk(chunk_losses, graded_steps)
                if stepped is not None:
                    norm_before_sum += stepped[0]
                    norm_after_sum += stepped[1]
                    optimizer_steps += 1
                chunk_losses = []
                # backward() freed the graph the carry still points into; cut it before the
                # next chunk starts recomputing from here. Required under accumulation too --
                # only the gradients persist across chunks, never the graph.
                policy.detach_actor_hidden_state()

            # Ordering mirrors the rollout exactly: act on obs[t], then apply dones[t]. Masking
            # (not reset()) keeps the graph alive for the environments that did not terminate.
            policy.mask_actor_hidden_state(dones)

        if chunk_losses and self.flush_tail:
            tail_chunk_size = len(chunk_losses)
            stepped = self._backward_chunk(chunk_losses, graded_steps)
            if stepped is not None:
                norm_before_sum += stepped[0]
                norm_after_sum += stepped[1]
                optimizer_steps += 1
            policy.detach_actor_hidden_state()
        chunk_losses = []

        if self.accumulate_gradients and num_steps > 0:
            # The single step of the rollout, over gradients accumulated from every chunk.
            norm_before, norm_after = self._step()
            norm_before_sum += norm_before
            norm_after_sum += norm_after
            optimizer_steps += 1

        policy.detach_actor_hidden_state()

        refresh_time = 0.0
        if self.refresh_hidden_after_update:
            refresh_time = self._refresh_hidden()

        # Carry for the next rollout. Not checkpointed: on resume the env is reset, so a carry
        # from a different episode would be worse than starting from zeros.
        self._rollout_start_hidden = policy.get_actor_hidden_state()
        self.storage.clear()

        if self.lr_scheduler is not None and self.lr_scheduler_step_unit == "update":
            self.lr_scheduler.step()
            self.learning_rate = self.optimizer.param_groups[0]["lr"]

        denom = max(num_steps, 1)
        opt_denom = max(optimizer_steps, 1)
        losses = {"behavior_loss": behavior_loss_sum / denom}
        stats = {
            "action_l2": action_l2_sum / denom,
            "action_err_max": action_err_max,
            "grad_norm_before_clip": norm_before_sum / opt_denom,
            "grad_norm_after_clip": norm_after_sum / opt_denom,
            "optimizer_steps": torch.tensor(float(optimizer_steps), device=self.device),
            "tail_chunk_size": torch.tensor(float(tail_chunk_size), device=self.device),
            "hidden_refresh_time": torch.tensor(refresh_time, device=self.device),
            # Invariant, logged so a regression shows up on the dashboard rather than in silence:
            # the environment never executes a teacher action in this algorithm.
            "teacher_state_ratio": zero.clone(),
        }
        return losses, stats

    def _refresh_hidden(self):
        """Regenerate the carry from the rollout using the post-update weights. Returns seconds.

        The timing is synchronised on CUDA on purpose: this number exists so the cost of the
        refresh can be weighed against its benefit, and an unsynchronised wall clock around a
        loop of asynchronous kernel launches would report a fraction of the real cost -- exactly
        the wrong answer for the decision it informs.
        """
        cuda = torch.cuda.is_available() and str(self.device).startswith("cuda")
        if cuda:
            torch.cuda.synchronize(self.device)
        start = time.time()

        policy = self.actor_critic
        with torch.no_grad():
            policy.set_actor_hidden_state(self._rollout_start_hidden)
            for student_obs, _, dones in self.storage.iter_timesteps():
                policy.act_inference(student_obs)
                policy.mask_actor_hidden_state(dones)

        if cuda:
            torch.cuda.synchronize(self.device)
        return time.time() - start

    """
    Checkpointing and mode switching
    """

    def state_dict(self):
        # Teacher weights are deliberately absent: they already live in the teacher's own run,
        # and keeping them out means a distillation checkpoint is a plain student actor-critic
        # checkpoint that OnPolicyRunner and the exporters can consume unchanged.
        state_dict = {
            "model_state_dict": self.actor_critic.state_dict(),
            "optimizer_state_dict": self.optimizer.state_dict(),
        }
        if self._ema_state is not None:
            # The EMA weights are the deployable ones, so they take the `model_state_dict` slot
            # that OnPolicyRunner and the exporters read. The raw weights ride along under a
            # separate key purely so training can resume where it left off -- resuming from an
            # average, with an optimizer state that belongs to the raw weights, would not.
            state_dict["model_state_dict"] = {k: v.clone() for k, v in self._ema_state.items()}
            state_dict["raw_model_state_dict"] = self.actor_critic.state_dict()
        if self.lr_scheduler is not None:
            state_dict["lr_scheduler_state_dict"] = self.lr_scheduler.state_dict()
        return state_dict

    def load_state_dict(self, state_dict):
        # A checkpoint written with EMA on carries both; prefer the raw weights so that a
        # resumed run continues the trajectory the optimizer state describes.
        weights = state_dict.get("raw_model_state_dict", state_dict["model_state_dict"])
        self.actor_critic.load_state_dict(weights)
        if self._ema_state is not None:
            source = state_dict["model_state_dict"] if "raw_model_state_dict" in state_dict else weights
            self._ema_state = {k: v.detach().clone().to(self.device) for k, v in source.items()}
        if "optimizer_state_dict" in state_dict:
            self.optimizer.load_state_dict(state_dict["optimizer_state_dict"])
        if self.lr_scheduler is not None and "lr_scheduler_state_dict" in state_dict:
            self.lr_scheduler.load_state_dict(state_dict["lr_scheduler_state_dict"])
        elif "lr_scheduler_state_dict" in state_dict:
            print("Warning: lr scheduler state dict found but no lr scheduler is configured. Ignored.")
        self._rollout_start_hidden = None

    def distributed_data_parallel(self):
        raise NotImplementedError(
            "Distillation is single-GPU for now. The interface is kept so OnPolicyRunner fails"
            " loudly here instead of silently training with unsynchronised gradients."
        )

    def train_mode(self):
        self.actor_critic.train()
        self.teacher.policy.eval()  # the teacher is frozen and never leaves eval mode

    def test_mode(self):
        self.actor_critic.eval()
        self.teacher.policy.eval()
