"""Teacher-student distillation with stateful truncated BPTT.

Scope: privileged teacher -> deployable student, behaviour cloning only. There is no critic,
no GAE, no PPO surrogate and no RL fine-tuning stage, so this algorithm deliberately does not
inherit from :class:`~instinct_rl.algorithms.ppo.PPO` or
:class:`~instinct_rl.algorithms.tppo.TPPO`.

Two properties drive the design, both of which matter far more for a *recurrent* student than
for an MLP one:

1. **The student's carry is recomputed, never replayed from the buffer.** PPO's recurrent
   minibatch generator starts every BPTT segment from the hidden state saved during rollout.
   After a few epochs of updates those saved states were produced by stale weights. Here the
   rollout is replayed forward in time and the carry is produced by the weights currently
   being trained. The residual staleness is one optimizer step at each TBPTT chunk boundary --
   not zero, but bounded and small (see ``refresh_hidden_after_update``).

2. **The environment always executes the student's action.** The teacher only ever produces
   labels. Mixing teacher actions into the rollout (as TPPO's ``teacher_act_prob`` does) makes
   the student's RNN learn its memory on state sequences generated by a mixture policy, while
   at deployment the sequence is student-only. Because a carry is a cumulative quantity, that
   mismatch compounds over time.

The teacher is an independent, frozen policy object. It is never touched by ``update()``, so
its own recurrent carry stays continuous across iterations, and its architecture is completely
decoupled from the student's.
"""

import os
import os.path as osp
import time

import torch
import torch.distributed as dist
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import yaml

import instinct_rl.modules as modules
from instinct_rl.storage.distillation_storage import DistillationStorage
from instinct_rl.utils.utils import get_subobs_size


def _is_critic_key(key: str) -> bool:
    """Whether a state-dict key belongs to the value-function half of an actor-critic."""
    return key.startswith(("critic", "critics", "memory_c", "critic_encoders"))


class TeacherPolicy:
    """A frozen, checkpoint-loaded policy that only ever produces deterministic action labels.

    Owns everything teacher-side that the rest of the system should not have to think about:
    building the network, loading the checkpoint, loading and freezing the teacher's *own*
    observation normalizer, and maintaining its recurrent carry across the whole training run.

    Observation normalization ownership: the teacher normalizes its input itself, with the
    normalizer stored in its checkpoint. The runner must therefore *not* configure a
    normalizer for the observation group that feeds the teacher, or the observations get
    normalized twice. :class:`~instinct_rl.runners.distillation_runner.DistillationRunner`
    checks this at construction time.
    """

    def __init__(
        self,
        policy_class_name,
        policy_cfg,
        obs_format,
        num_actions,
        num_rewards,
        logdir=None,
        checkpoint=None,
        device="cpu",
    ):
        self.device = device
        self.logdir = logdir
        self.checkpoint = checkpoint

        policy_cfg = dict(policy_cfg)
        # The teacher's actor was trained on its own "policy" group. When distilling from a
        # privileged teacher, that group is whatever group of the *current* env we feed it
        # (usually "critic"); the caller has already resolved this into `obs_format`.
        policy_cfg.setdefault("obs_format", obs_format)
        # Keep the *raw* observation format: the normalizer is sized on it. Reading it back off
        # the built policy would not work -- ActorCriticRecurrent.obs_segments describes its MLP
        # head's input (the RNN latent), not the observations entering the network.
        self.obs_format = policy_cfg["obs_format"]

        self.policy = modules.build_actor_critic(
            policy_class_name,
            policy_cfg,
            policy_cfg["obs_format"],
            num_actions=num_actions,
            num_rewards=num_rewards,
        ).to(device)
        self.normalizer = None

        if logdir is None:
            print(
                "\033[43;33mDistillation warning: no teacher checkpoint given; the teacher is randomly"
                " initialized and its labels are meaningless.\033[0m"
            )
        else:
            self._load()

        self.policy.eval()
        self.policy.requires_grad_(False)

    """
    Checkpoint loading
    """

    def _resolve_model_path(self):
        if self.checkpoint is not None:
            return self.checkpoint if osp.isabs(self.checkpoint) else osp.join(self.logdir, self.checkpoint)
        model_files = [f for f in os.listdir(self.logdir) if f.endswith(".pt") and f.startswith("model_")]
        if not model_files:
            raise FileNotFoundError(f"No model_*.pt checkpoint found in teacher logdir {self.logdir}")
        model_files.sort(key=lambda f: int(f.split(".")[0].split("_")[1]))
        return osp.join(self.logdir, model_files[-1])

    def _load(self):
        model_path = self._resolve_model_path()
        print(f"Distillation: loading teacher policy from {model_path}")
        state_dict = torch.load(model_path, map_location="cpu")

        # The teacher's critic is never used for distillation, and its observation group may
        # not even exist in the distillation env, so a shape mismatch there is not an error.
        # Everything on the actor path, however, must match exactly -- a silently unloaded
        # actor layer would produce plausible-looking but wrong labels for the entire run.
        missing, unexpected = self.policy.load_state_dict(state_dict["model_state_dict"], strict=False)
        actor_missing = [k for k in missing if not _is_critic_key(k)]
        actor_unexpected = [k for k in unexpected if not _is_critic_key(k)]
        if actor_missing or actor_unexpected:
            raise RuntimeError(
                "Teacher checkpoint does not match the configured teacher architecture on the actor"
                f" path.\n  missing keys:    {actor_missing}\n  unexpected keys: {actor_unexpected}\n"
                "Check `teacher_policy_class_name` and `teacher_policy` against the run that produced"
                f" {model_path}."
            )

        self._load_normalizer(state_dict)

    def _load_normalizer(self, state_dict):
        if "policy_normalizer_state_dict" not in state_dict:
            return
        agent_cfg_path = osp.join(self.logdir, "params", "agent.yaml")
        if not osp.isfile(agent_cfg_path):
            raise FileNotFoundError(
                f"Teacher checkpoint carries a policy normalizer but {agent_cfg_path} is missing, so"
                " the normalizer class/kwargs cannot be reconstructed."
            )
        with open(agent_cfg_path) as f:
            agent_cfg = yaml.full_load(f)
        normalizer_cfg = dict(agent_cfg["normalizers"]["policy"])
        self.normalizer = modules.build_normalizer(
            input_shape=get_subobs_size(self.obs_format["policy"]),
            normalizer_class_name=normalizer_cfg.pop("class_name"),
            normalizer_kwargs=normalizer_cfg,
        )
        self.normalizer.to(self.device)
        self.normalizer.load_state_dict(state_dict["policy_normalizer_state_dict"])
        self.normalizer.eval()
        self.normalizer.requires_grad_(False)
        print("Distillation: loaded and froze the teacher's own observation normalizer.")

    """
    Labelling
    """

    @torch.no_grad()
    def act_inference(self, obs):
        """Deterministic teacher action mean, and the only thing the student is trained on."""
        if self.normalizer is not None:
            obs = self.normalizer(obs)
        return self.policy.act_inference(obs)

    def reset(self, dones):
        """Reset the teacher's own carry at episode boundaries. Called from rollout only."""
        self.policy.reset(dones)


class Distillation:
    """Behaviour-cloning a privileged teacher into a deployable (usually recurrent) student."""

    def __init__(
        self,
        actor_critic,
        # -- teacher
        teacher_logdir=None,
        teacher_checkpoint=None,
        teacher_policy_class_name="ActorCriticRecurrent",
        teacher_policy=None,
        teacher_obs_source="critic",
        # -- loss
        loss_type="mse_sum",
        # -- optimisation
        gradient_length=24,
        normalize_accumulated_loss=True,
        flush_tail=True,
        learning_rate=3.0e-4,
        max_grad_norm=1.0,
        optimizer_class_name="Adam",
        freeze_action_std=True,
        # -- recurrent bookkeeping
        refresh_hidden_after_update=False,
        # -- lr schedule
        lr_scheduler_class_name=None,
        lr_scheduler=None,
        lr_scheduler_step_unit="optimizer_step",
        device="cpu",
        **kwargs,
    ):
        """
        Args:
            teacher_obs_source: which observation group of the *current* env feeds the teacher's
                actor. "critic" for the usual privileged-teacher setup, "policy" when teacher and
                student share an observation space.
            gradient_length: TBPTT chunk length, in environment steps. Decoupled from
                ``num_steps_per_env`` on purpose: the rollout length sets how much data an
                iteration sees, this sets how deep gradients flow.
            normalize_accumulated_loss: average the per-step losses over a chunk instead of
                summing them, so the effective step size does not scale with ``gradient_length``.
            flush_tail: run a final optimizer step on the leftover steps when the rollout is not
                an exact multiple of ``gradient_length``. Without it those steps produce no
                gradient at all while still appearing in the logged loss.
            refresh_hidden_after_update: after all optimizer steps, replay the rollout once more
                under ``no_grad`` with the final weights and use *that* as the next rollout's
                carry. Costs one extra sequential forward pass over the rollout and only removes
                a one-optimizer-step-old carry, so it is off by default; keep it as an ablation.
        """
        if kwargs:
            print("\033[43;33mWarning: Distillation init got extra kwargs:", kwargs.keys(), "\033[0m")

        self.device = device
        self.actor_critic = actor_critic
        self.actor_critic.to(self.device)

        self.teacher_obs_source = teacher_obs_source
        if teacher_obs_source not in ("policy", "critic"):
            raise ValueError(f"teacher_obs_source must be 'policy' or 'critic', got {teacher_obs_source!r}")

        self.loss_type = loss_type
        self.gradient_length = gradient_length
        self.normalize_accumulated_loss = normalize_accumulated_loss
        self.flush_tail = flush_tail
        self.learning_rate = learning_rate
        self.max_grad_norm = max_grad_norm
        self.refresh_hidden_after_update = refresh_hidden_after_update
        self.lr_scheduler_step_unit = lr_scheduler_step_unit
        if lr_scheduler_step_unit not in ("optimizer_step", "update"):
            raise ValueError(
                f"lr_scheduler_step_unit must be 'optimizer_step' or 'update', got {lr_scheduler_step_unit!r}"
            )

        # The behaviour-cloning loss is a function of the student's action *mean* only, so the
        # exploration std never receives a gradient. Freezing it makes that explicit instead of
        # leaving a parameter that looks trainable but silently never moves.
        if freeze_action_std and hasattr(self.actor_critic, "std"):
            self.actor_critic.std.requires_grad_(False)

        self.trainable_parameters = [p for p in self.actor_critic.parameters() if p.requires_grad]
        self.optimizer = getattr(optim, optimizer_class_name)(self.trainable_parameters, lr=learning_rate)

        self.lr_scheduler = None
        if lr_scheduler_class_name is not None:
            self.lr_scheduler = getattr(optim.lr_scheduler, lr_scheduler_class_name)(
                self.optimizer, **(lr_scheduler or {})
            )

        # Teacher is built lazily in init_storage(), where the env's obs_format is available.
        self._teacher_cfg = dict(
            logdir=teacher_logdir,
            checkpoint=teacher_checkpoint,
            policy_class_name=teacher_policy_class_name,
            policy_cfg=dict(teacher_policy or {}),
        )
        self.teacher = None
        self.storage = None

        # The carry the current rollout started from. `update()` replays from here rather than
        # from wherever the rollout left the policy, so the replay reproduces the same state
        # sequence with fresh weights. None means "zeros", which is also the state at iteration 0.
        self._rollout_start_hidden = None
        self._pending_student_obs = None
        self._pending_teacher_mean = None

        self.current_learning_iteration = 0
        self.optimizer_step_count = 0

    """
    Setup
    """

    def init_storage(self, num_envs, num_transitions_per_env, obs_format, num_actions, num_rewards=1):
        student_obs_size = int(get_subobs_size(obs_format["policy"]))
        self.storage = DistillationStorage(
            num_envs,
            num_transitions_per_env,
            student_obs_shape=(student_obs_size,),
            actions_shape=(num_actions,),
            device=self.device,
        )

        teacher_cfg = dict(self._teacher_cfg)
        policy_cfg = teacher_cfg.pop("policy_cfg")
        if "obs_format" not in policy_cfg:
            # The teacher's actor consumes the chosen group of the current env. Its critic is
            # never evaluated, so pointing it at the same group is harmless and avoids forcing
            # the user to restate the teacher's full obs_format in the config.
            if self.teacher_obs_source not in obs_format:
                raise KeyError(
                    f"teacher_obs_source={self.teacher_obs_source!r} is not an observation group of this"
                    f" env (available: {list(obs_format)}). Either change it or provide an explicit"
                    " `teacher_policy.obs_format`."
                )
            group = obs_format[self.teacher_obs_source]
            policy_cfg["obs_format"] = {"policy": group, "critic": group}

        self.teacher = TeacherPolicy(
            policy_cfg=policy_cfg,
            obs_format=policy_cfg["obs_format"],
            num_actions=num_actions,
            num_rewards=num_rewards,
            device=self.device,
            **teacher_cfg,
        )

    """
    Rollout
    """

    def act(self, obs, critic_obs):
        """Return the action the environment will execute -- always the student's, never the teacher's."""
        teacher_obs = critic_obs if self.teacher_obs_source == "critic" else obs
        if teacher_obs is None:
            raise ValueError(
                "teacher_obs_source='critic' but the environment produced no critic observations."
            )

        self._pending_teacher_mean = self.teacher.act_inference(teacher_obs).detach()
        self._pending_student_obs = obs
        # Sampled, not the mean: the exploration noise is what gives the student state coverage
        # beyond the trajectory band it would otherwise stay on. std is frozen, so this is a
        # constant-width perturbation throughout training.
        return self.actor_critic.act(obs).detach()

    def process_env_step(self, rewards, dones, infos, next_obs, next_critic_obs):
        self.storage.add(self._pending_student_obs, self._pending_teacher_mean, dones)
        self._pending_student_obs = None
        self._pending_teacher_mean = None
        # Student and teacher keep separate carries and are reset independently.
        self.actor_critic.reset(dones)
        self.teacher.reset(dones)

    def compute_returns(self, last_critic_obs):
        """No-op. Behaviour cloning has no value function.

        Kept so :class:`~instinct_rl.runners.on_policy_runner.OnPolicyRunner` can drive this
        algorithm unchanged; duplicating its ~90-line rollout/bookkeeping loop just to delete
        one call would be a worse trade than this two-line stub.
        """
        return None

    """
    Update
    """

    def _behavior_loss(self, student_mean, teacher_mean):
        """Per-timestep behaviour loss: reduce over the action dimension, mean over envs."""
        diff = student_mean - teacher_mean
        if self.loss_type == "mse_sum":
            per_env = diff.square().sum(dim=-1)
        elif self.loss_type == "mse":
            per_env = diff.square().mean(dim=-1)
        elif self.loss_type == "l1":
            per_env = diff.abs().sum(dim=-1)
        elif self.loss_type == "huber":
            per_env = F.huber_loss(student_mean, teacher_mean, reduction="none").sum(dim=-1)
        else:
            raise ValueError(f"Unknown loss_type: {self.loss_type!r}")
        return per_env.mean()

    def _optimize(self, chunk_losses):
        """One optimizer step over an accumulated TBPTT chunk. Returns (norm_before, norm_after)."""
        stacked = torch.stack(chunk_losses)
        loss = stacked.mean() if self.normalize_accumulated_loss else stacked.sum()

        self.optimizer.zero_grad(set_to_none=True)
        loss.backward()

        if dist.is_initialized():
            raise NotImplementedError(
                "Distillation does not support distributed training yet. Gradients must be"
                " all-reduced before *each* of the T/gradient_length optimizer steps in an update,"
                " not once per update; see HANDOFF.md."
            )

        # clip_grad_norm_ returns the total norm *before* clipping, so both numbers come free.
        max_norm = self.max_grad_norm if self.max_grad_norm is not None else float("inf")
        norm_before = nn.utils.clip_grad_norm_(self.trainable_parameters, max_norm)
        norm_after = torch.clamp(norm_before, max=max_norm)

        self.optimizer.step()
        self.optimizer_step_count += 1
        if self.lr_scheduler is not None and self.lr_scheduler_step_unit == "optimizer_step":
            self.lr_scheduler.step()
            self.learning_rate = self.optimizer.param_groups[0]["lr"]

        return norm_before.detach(), norm_after.detach()

    def update(self, current_learning_iteration):
        self.current_learning_iteration = current_learning_iteration
        policy = self.actor_critic

        # Replay from where the rollout began, not from where it ended: the point is to
        # regenerate the carry with the weights being trained.
        policy.set_actor_hidden_state(self._rollout_start_hidden)

        zero = torch.zeros((), device=self.device)
        behavior_loss_sum = zero.clone()
        action_l2_sum = zero.clone()
        action_err_max = zero.clone()
        norm_before_sum = zero.clone()
        norm_after_sum = zero.clone()
        num_steps = 0
        optimizer_steps = 0
        tail_chunk_size = 0
        chunk_losses = []

        for student_obs, teacher_mean, dones in self.storage.iter_timesteps():
            student_mean = policy.act_inference(student_obs)
            step_loss = self._behavior_loss(student_mean, teacher_mean)
            chunk_losses.append(step_loss)
            num_steps += 1

            with torch.no_grad():
                diff = student_mean - teacher_mean
                behavior_loss_sum += step_loss.detach()
                action_l2_sum += diff.norm(dim=-1).mean()
                action_err_max = torch.maximum(action_err_max, diff.abs().max())

            if len(chunk_losses) == self.gradient_length:
                norm_before, norm_after = self._optimize(chunk_losses)
                norm_before_sum += norm_before
                norm_after_sum += norm_after
                optimizer_steps += 1
                chunk_losses = []
                # backward() freed the graph the carry still points into; cut it before the
                # next chunk starts recomputing from here.
                policy.detach_actor_hidden_state()

            # Ordering mirrors the rollout exactly: act on obs[t], then apply dones[t]. Masking
            # (not reset()) keeps the graph alive for the environments that did not terminate.
            policy.mask_actor_hidden_state(dones)

        if chunk_losses and self.flush_tail:
            tail_chunk_size = len(chunk_losses)
            norm_before, norm_after = self._optimize(chunk_losses)
            norm_before_sum += norm_before
            norm_after_sum += norm_after
            optimizer_steps += 1
            policy.detach_actor_hidden_state()
        chunk_losses = []

        policy.detach_actor_hidden_state()

        refresh_time = 0.0
        if self.refresh_hidden_after_update:
            refresh_time = self._refresh_hidden()

        # Carry for the next rollout. Not checkpointed: on resume the env is reset, so a carry
        # from a different episode would be worse than starting from zeros.
        self._rollout_start_hidden = policy.get_actor_hidden_state()
        self.storage.clear()

        if self.lr_scheduler is not None and self.lr_scheduler_step_unit == "update":
            self.lr_scheduler.step()
            self.learning_rate = self.optimizer.param_groups[0]["lr"]

        denom = max(num_steps, 1)
        opt_denom = max(optimizer_steps, 1)
        losses = {"behavior_loss": behavior_loss_sum / denom}
        stats = {
            "action_l2": action_l2_sum / denom,
            "action_err_max": action_err_max,
            "grad_norm_before_clip": norm_before_sum / opt_denom,
            "grad_norm_after_clip": norm_after_sum / opt_denom,
            "optimizer_steps": torch.tensor(float(optimizer_steps), device=self.device),
            "tail_chunk_size": torch.tensor(float(tail_chunk_size), device=self.device),
            "hidden_refresh_time": torch.tensor(refresh_time, device=self.device),
            # Invariant, logged so a regression shows up on the dashboard rather than in silence:
            # the environment never executes a teacher action in this algorithm.
            "teacher_state_ratio": zero.clone(),
        }
        return losses, stats

    def _refresh_hidden(self):
        """Regenerate the carry from the rollout using the post-update weights. Returns seconds.

        The timing is synchronised on CUDA on purpose: this number exists so the cost of the
        refresh can be weighed against its benefit, and an unsynchronised wall clock around a
        loop of asynchronous kernel launches would report a fraction of the real cost -- exactly
        the wrong answer for the decision it informs.
        """
        cuda = torch.cuda.is_available() and str(self.device).startswith("cuda")
        if cuda:
            torch.cuda.synchronize(self.device)
        start = time.time()

        policy = self.actor_critic
        with torch.no_grad():
            policy.set_actor_hidden_state(self._rollout_start_hidden)
            for student_obs, _, dones in self.storage.iter_timesteps():
                policy.act_inference(student_obs)
                policy.mask_actor_hidden_state(dones)

        if cuda:
            torch.cuda.synchronize(self.device)
        return time.time() - start

    """
    Checkpointing and mode switching
    """

    def state_dict(self):
        # Teacher weights are deliberately absent: they already live in the teacher's own run,
        # and keeping them out means a distillation checkpoint is a plain student actor-critic
        # checkpoint that OnPolicyRunner and the exporters can consume unchanged.
        state_dict = {
            "model_state_dict": self.actor_critic.state_dict(),
            "optimizer_state_dict": self.optimizer.state_dict(),
        }
        if self.lr_scheduler is not None:
            state_dict["lr_scheduler_state_dict"] = self.lr_scheduler.state_dict()
        return state_dict

    def load_state_dict(self, state_dict):
        self.actor_critic.load_state_dict(state_dict["model_state_dict"])
        if "optimizer_state_dict" in state_dict:
            self.optimizer.load_state_dict(state_dict["optimizer_state_dict"])
        if self.lr_scheduler is not None and "lr_scheduler_state_dict" in state_dict:
            self.lr_scheduler.load_state_dict(state_dict["lr_scheduler_state_dict"])
        elif "lr_scheduler_state_dict" in state_dict:
            print("Warning: lr scheduler state dict found but no lr scheduler is configured. Ignored.")
        self._rollout_start_hidden = None

    def distributed_data_parallel(self):
        raise NotImplementedError(
            "Distillation is single-GPU for now. The interface is kept so OnPolicyRunner fails"
            " loudly here instead of silently training with unsynchronised gradients."
        )

    def train_mode(self):
        self.actor_critic.train()
        self.teacher.policy.eval()  # the teacher is frozen and never leaves eval mode

    def test_mode(self):
        self.actor_critic.eval()
        self.teacher.policy.eval()
